import type { ClientQuestionnaire } from "./types";

/** Начальное состояние анкеты для MVP (мок / сиды). */
export const questionnaireDefaults = {
  basics: {
    firstName: "",
    preferredAddressing: "neutral",
    age: 0,
    heightCm: 0,
    weightKg: 0,
    cityOrRegion: "",
  },
  goalAndDuration: {
    primaryGoal: "",
    programDurationDays: 14,
    desiredOutcome: "",
    comfortablePace: "мягкий",
  },
  medicalParticularities: {
    hasMedicalParticularities: false,
    medicalParticularitiesDescription: "",
    foodAllergies: "",
    intolerances: "",
    medicalDietaryRestrictions: "",
  },
  dayScheduleAndWork: {
    wakeTime: "",
    sleepTime: "",
    workType: "сидячая",
    workScheduleNotes: "",
    usualMealTimesNotes: "",
    activityLevel: "средний",
  },
  foodAndProducts: {
    mealsPerDay: 3,
    usualBreakfast: "",
    usualLunch: "",
    usualDinner: "",
    favoriteFoods: "",
    foodsNotEaten: "",
    sweetCraving: "иногда",
    eveningSnacks: "иногда",
    snacksAndTiming: "",
    commonNutritionChallenges: "",
  },
  budgetSeasonAndAvailability: {
    foodBudget: "средний",
    productAvailability: "обычные магазины",
    season: "авто",
    willingToBuyRareProducts: "иногда",
    needsSimpleProductSubstitutions: "да",
  },
  habitsDifficultiesAndSupport: {
    helpfulHabitsNotes: "",
    habitsHinderingProgressNotes: "",
    smokingNotes: "",
    alcoholNotes: "",
    frequentSweetenedDrinks: "иногда",
    fastFoodFrequency: "иногда",
    nightSnacks: "иногда",
    stressOvereating: "иногда",
    skippedBreakfastOrLunch: "иногда",
    insufficientSleep: "иногда",
    lowPhysicalActivity: "иногда",
    mainChallenges: "",
    whatOftenGetsInTheWay: "",
    reactionToSkips: "",
    preferredSupportTone: "мягкий",
  },
  cookingHabitsAndMethods: {
    usualCookingMethods: "",
    friedFoodFrequency: "sometimes",
    cookingTimeAvailable: "15_30_min",
    availableKitchenTools: "",
    sugarAddingFrequency: "sometimes",
    sweetDrinksFrequency: "sometimes",
    saltUsage: "moderate",
    spicySaucesAndSpicesUsage: "sometimes",
    easyToReplace: "",
    cookingMethodsToAvoid: "",
  },
} satisfies ClientQuestionnaire;
