import type { ProteinKey } from "./mealProtein";
import type {
  AvoidIfTag,
  BreakfastType,
  CatalogDish,
  CarbType,
  ContainsTag,
  MealFamily,
  ProteinType,
} from "./catalogTypes";

type MkMeta = {
  proteinType: ProteinType;
  carbType: CarbType;
  mealFamily: MealFamily;
  contains: ContainsTag[];
  avoidIf?: AvoidIfTag[];
  protein?: ProteinKey;
  breakfastType?: BreakfastType;
  starchKey?: string;
  containsEgg?: boolean;
  dishSubtype?: "syrniki" | "tvorogBake" | "fishMain";
};

const CONTAINS_TO_AVOID: Record<ContainsTag, AvoidIfTag> = {
  dairy: "lactose",
  gluten: "gluten",
  egg: "egg",
  nuts: "nuts",
  fish: "fish",
  seaFish: "seaFish",
  riverFish: "riverFish",
  seafood: "seafood",
  meat: "meat",
  legumes: "legumes",
};

function avoidIfFromContains(contains: ContainsTag[]): AvoidIfTag[] {
  return [...new Set(contains.map((c) => CONTAINS_TO_AVOID[c]))];
}

function defaultProtein(pt: ProteinType): ProteinKey {
  const map: Record<ProteinType, ProteinKey> = {
    chicken: "курица",
    turkey: "индейка",
    fish: "рыба",
    egg: "яйцо",
    dairy: "молочное",
    legumes: "бобовые",
    beef: "говядина",
    rabbit: "кролик",
    mixed: "смешанное",
    none: "смешанное",
  };
  return map[pt];
}

export function mk(dish: string, diversityKey: string, m: MkMeta): CatalogDish {
  return {
    dish,
    diversityKey,
    protein: m.protein ?? defaultProtein(m.proteinType),
    proteinType: m.proteinType,
    carbType: m.carbType,
    mealFamily: m.mealFamily,
    contains: m.contains,
    avoidIf: m.avoidIf ?? avoidIfFromContains(m.contains),
    breakfastType: m.breakfastType,
    starchKey: m.starchKey,
    containsEgg: m.containsEgg ?? m.contains.includes("egg"),
    dishSubtype: m.dishSubtype,
  };
}

export const BREAKFAST_CATALOG: CatalogDish[] = [
  mk("Ленивая овсянка с йогуртом и ягодами", "завтр-ленивая-овсянка", {
    proteinType: "dairy",
    carbType: "oats",
    mealFamily: "porridge",
    contains: ["dairy"],
    breakfastType: "porridge",
  }),
  mk("Творог с фруктом и орехами", "завтр-творог-орехи", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy", "nuts"],
    breakfastType: "dairy",
  }),
  mk("Омлет с сыром и овощами", "завтр-омлет-сыр", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg", "dairy"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Цельнозерновой тост с яйцом и овощами", "завтр-тост-яйцо", {
    proteinType: "egg",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["egg", "gluten"],
    breakfastType: "toast",
    containsEgg: true,
  }),
  mk("Гречневая каша с яйцом и огурцом", "завтр-гречка-яйцо", {
    proteinType: "egg",
    carbType: "buckwheat",
    mealFamily: "porridge",
    contains: ["egg"],
    breakfastType: "porridge",
    containsEgg: true,
  }),
  mk("Пшённая каша с яблоком", "завтр-пшено", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Рисовая каша с грушей", "завтр-рис-каша", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Сырники запечённые с ягодами", "завтр-сырники", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "baked",
    contains: ["dairy", "egg", "gluten"],
    breakfastType: "baked",
    dishSubtype: "syrniki",
  }),
  mk("Творожная запеканка с яблоком", "завтр-запеканка", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "casserole",
    contains: ["dairy", "egg"],
    breakfastType: "baked",
    dishSubtype: "tvorogBake",
  }),
  mk("Йогурт-боул с фруктом и семечками", "завтр-йогурт-боул", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
    breakfastType: "bowl",
  }),
  mk("Яйца всмятку с овощами и сыром", "завтр-яйца-сыр", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg", "dairy"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Овсянка на воде с бананом", "завтр-овсянка-банан", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Греческий йогурт с ягодами", "завтр-йогурт-ягоды", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
    breakfastType: "bowl",
  }),
  mk("Омлет с шпинатом и помидорами", "завтр-омлет-шпинат", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Ленивая овсянка на воде с ягодами", "завтр-ленивая-овсянка-бл", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Омлет с овощами", "завтр-омлет-овощи", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Цельнозерновой тост с авокадо и яйцом", "завтр-тост-авокадо", {
    proteinType: "egg",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["egg", "gluten"],
    breakfastType: "toast",
    containsEgg: true,
  }),
  mk("Овсяноблин с ягодами", "завтр-овсяноблин", {
    proteinType: "egg",
    carbType: "oats",
    mealFamily: "baked",
    contains: ["egg", "gluten"],
    breakfastType: "baked",
    containsEgg: true,
  }),
  mk("Яйца всмятку с овощами", "завтр-яйца-овощи", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Смузи: банан, овсянка, вода", "завтр-смузи", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "bowl",
    contains: [],
    breakfastType: "bowl",
  }),
  mk("Омлет с грибами", "завтр-омлет-грибы", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Овсянка с яблоком и корицей", "завтр-овсянка-яблоко", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Манная каша с ягодами", "завтр-манка-ягоды", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "porridge",
    contains: ["dairy", "gluten"],
    breakfastType: "porridge",
  }),
  mk("Яичница с помидорами", "завтр-яичница", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Скрэмбл с зеленью", "завтр-скрэмбл", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Рисовые хлебцы с авокадо", "завтр-хлебцы-авокадо", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "toast",
    contains: [],
    breakfastType: "toast",
  }),
  mk("Гречка с тушёными грибами", "завтр-гречка-грибы", {
    proteinType: "none",
    carbType: "buckwheat",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Тост с хумусом и овощами", "завтр-тост-хумус", {
    proteinType: "legumes",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["legumes", "gluten"],
    breakfastType: "toast",
  }),
  mk("Киноа с тёплыми овощами и зеленью", "завтр-киноа", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "bowl",
    contains: [],
    breakfastType: "bowl",
  }),
  mk("Сэндвич с индейкой и овощами", "завтр-сэндвич-индейка", {
    proteinType: "turkey",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["meat", "gluten"],
    breakfastType: "toast",
  }),
  mk("Смузи-чаша: ягоды и овсянка на воде", "завтр-смузи-чаша", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "bowl",
    contains: [],
    breakfastType: "bowl",
  }),
  mk("Запечённый омлет-ролл с овощами", "завтр-омлет-ролл", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "casserole",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Перловка с тыквой", "завтр2-перловка-тыква", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Гречневая каша с кабачком", "завтр2-гречка-кабачок", {
    proteinType: "none",
    carbType: "buckwheat",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Тост с творожным сыром и зеленью", "завтр2-тост-сыр", {
    proteinType: "dairy",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["dairy", "gluten"],
    breakfastType: "toast",
  }),
  mk("Яйцо пашот с овощным салатом", "завтр2-пашот-салат", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "salad",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Творожный смузи с бананом", "завтр2-творожный-смузи", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
    breakfastType: "dairy",
  }),
  mk("Овсяные оладьи с ягодами", "завтр2-овсян-оладьи", {
    proteinType: "egg",
    carbType: "oats",
    mealFamily: "baked",
    contains: ["egg", "gluten", "dairy"],
    breakfastType: "baked",
    containsEgg: true,
  }),
  mk("Йогурт с мюсли", "завтр2-йогурт-мюсли", {
    proteinType: "dairy",
    carbType: "oats",
    mealFamily: "dairyBowl",
    contains: ["dairy", "gluten"],
    breakfastType: "bowl",
  }),
  mk("Гречка с творогом и зеленью", "завтр2-гречка-творог", {
    proteinType: "dairy",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["dairy"],
    breakfastType: "bowl",
  }),
  mk("Пшенная каша с тыквой", "завтр2-пшено-тыква", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Омлет в духовке с брокколи", "завтр2-омлет-духовка", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Рисовые хлебцы с творожным сыром", "завтр2-хлебцы-творожный-сыр", {
    proteinType: "dairy",
    carbType: "rice",
    mealFamily: "toast",
    contains: ["dairy"],
    breakfastType: "toast",
  }),
  mk("Салат из огурца и яйца", "завтр2-салат-огурец-яйцо", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "salad",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Каша из полбы с яблоком", "завтр2-полба-яблоко", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "porridge",
    contains: ["gluten"],
    breakfastType: "porridge",
  }),
  mk("Тост с авокадо", "завтр2-тост-авокадо", {
    proteinType: "none",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["gluten"],
    breakfastType: "toast",
  }),
  mk("Запеканка из кабачков с сыром", "завтр2-кабачок-сыр", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "casserole",
    contains: ["dairy", "egg"],
    breakfastType: "baked",
    containsEgg: true,
  }),
  mk("Ряженка с сухофруктами", "завтр2-ряженка-сухофрукты", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
    breakfastType: "dairy",
  }),
  mk("Бутерброд с ветчиной из индейки", "завтр2-бутерброд-индейка", {
    proteinType: "turkey",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["meat", "gluten"],
    breakfastType: "toast",
  }),
  mk("Овсянка с тыквой и корицей", "завтр2-овсянка-тыква", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Сырники на сковороде без жарки", "завтр2-сырники-сковорода", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "baked",
    contains: ["dairy", "egg", "gluten"],
    breakfastType: "baked",
    dishSubtype: "syrniki",
  }),
  mk("Гранола с йогуртом", "завтр2-гранола-йогурт", {
    proteinType: "dairy",
    carbType: "oats",
    mealFamily: "dairyBowl",
    contains: ["dairy", "gluten", "nuts"],
    breakfastType: "bowl",
  }),
  mk("Овсяная каша с изюмом", "завтр3-овсянка-изюм", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Гречневая каша с зеленью", "завтр3-гречка-зелень", {
    proteinType: "none",
    carbType: "buckwheat",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Рисовая каша на молоке с корицей", "завтр3-рис-каша-молоко", {
    proteinType: "dairy",
    carbType: "rice",
    mealFamily: "porridge",
    contains: ["dairy"],
    breakfastType: "porridge",
  }),
  mk("Яйцо всмятку с тостом", "завтр3-яйцо-тост", {
    proteinType: "egg",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["egg", "gluten"],
    breakfastType: "toast",
    containsEgg: true,
  }),
  mk("Творог с бананом", "завтр3-творог-банан", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
    breakfastType: "dairy",
  }),
  mk("Йогурт с мёдом-заменителем", "завтр3-йогурт-мед", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
    breakfastType: "bowl",
  }),
  mk("Омлет с ветчиной из индейки", "завтр3-омлет-ветчина", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg", "meat"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Сэндвич с сыром и помидором", "завтр3-сэндвич-сыр", {
    proteinType: "dairy",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["dairy", "gluten"],
    breakfastType: "toast",
  }),
  mk("Рисовые хлебцы с творогом", "завтр3-хлебцы-творог", {
    proteinType: "dairy",
    carbType: "rice",
    mealFamily: "toast",
    contains: ["dairy"],
    breakfastType: "toast",
  }),
  mk("Салат из капусты с морковью и яйцом", "завтр3-салат-капуста", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "salad",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Ленивая гречка с кефиром", "завтр3-ленивая-гречка", {
    proteinType: "dairy",
    carbType: "buckwheat",
    mealFamily: "porridge",
    contains: ["dairy"],
    breakfastType: "porridge",
  }),
  mk("Овсянка с тёртым яблоком", "завтр3-овсянка-яблоко", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Запеканка из тыквы", "завтр3-тыква-запеканка", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "casserole",
    contains: ["egg"],
    breakfastType: "baked",
    containsEgg: true,
  }),
  mk("Сырники из духовки с ягодным соусом", "завтр3-сырники-соус", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "baked",
    contains: ["dairy", "egg", "gluten"],
    breakfastType: "baked",
    dishSubtype: "syrniki",
  }),
  mk("Творожный крем с какао", "завтр3-творожный-какао", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
    breakfastType: "dairy",
  }),
  mk("Яичница с болгарским перцем", "завтр3-яичница-перец", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Тост с яйцом пашот", "завтр3-тост-пашот", {
    proteinType: "egg",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["egg", "gluten"],
    breakfastType: "toast",
    containsEgg: true,
  }),
  mk("Кукурузная каша с маслом", "завтр3-кукурузная-каша", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Йогурт с бананом и мюсли", "завтр3-йогурт-банан", {
    proteinType: "dairy",
    carbType: "oats",
    mealFamily: "dairyBowl",
    contains: ["dairy", "gluten"],
    breakfastType: "bowl",
  }),
  mk("Омлет с кабачком", "завтр3-омлет-кабачок", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Гречка с яйцом и зеленью", "завтр3-гречка-яйцо-зелень", {
    proteinType: "egg",
    carbType: "buckwheat",
    mealFamily: "porridge",
    contains: ["egg"],
    breakfastType: "porridge",
    containsEgg: true,
  }),
  mk("Творог с огурцом", "завтр3-творог-огурец", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
    breakfastType: "dairy",
  }),
  mk("Хлебцы с сыром и зеленью", "завтр3-хлебцы-сыр", {
    proteinType: "dairy",
    carbType: "rice",
    mealFamily: "toast",
    contains: ["dairy"],
    breakfastType: "toast",
  }),
  mk("Пшённая каша с тыквой", "завтр3-пшено-тыква", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Овсянка с грушей", "завтр3-овсянка-груша", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Скрэмбл с ветчиной из индейки", "завтр3-скрэмбл-ветчина", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg", "meat"],
    breakfastType: "egg",
    containsEgg: true,
  }),
  mk("Рисовая каша с ягодами", "завтр3-рис-каша-ягоды", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Запечённый сыр с овощами", "завтр3-сыр-запеченный", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "casserole",
    contains: ["dairy"],
    breakfastType: "baked",
  }),
  mk("Бутерброд с курицей и огурцом", "завтр3-бутерброд-курица", {
    proteinType: "chicken",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["meat", "gluten"],
    breakfastType: "toast",
  }),
  mk("Смузи: кефир, банан и овсянка", "завтр3-смузи-кефир", {
    proteinType: "dairy",
    carbType: "oats",
    mealFamily: "bowl",
    contains: ["dairy"],
    breakfastType: "bowl",
  }),
  mk("Овсянка на воде с яблоком", "завтр4-овсянка-вода-яблоко", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Гречневая каша на воде с зеленью", "завтр4-гречка-вода-зелень", {
    proteinType: "none",
    carbType: "buckwheat",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Рисовая каша на воде с грушей", "завтр4-рис-каша-груша", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Пшённая каша на воде с тыквой", "завтр4-пшено-тыква", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "porridge",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Овсяная лепёшка с ягодами", "завтр4-овсяная-лепешка", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "baked",
    contains: [],
    breakfastType: "baked",
  }),
  mk("Рисовые хлебцы с авокадо и огурцом", "завтр4-хлебцы-авокадо", {
    proteinType: "none",
    carbType: "bread",
    mealFamily: "toast",
    contains: [],
    breakfastType: "toast",
  }),
  mk("Тост с хумусом и помидором", "завтр4-тост-хумус", {
    proteinType: "legumes",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["legumes", "gluten"],
    breakfastType: "toast",
  }),
  mk("Смузи: банан, вода и овсянка", "завтр4-смузи-вода", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "bowl",
    contains: [],
    breakfastType: "bowl",
  }),
  mk("Хумус с овощами и хлебцами", "завтр4-хумус-хлебцы", {
    proteinType: "legumes",
    carbType: "bread",
    mealFamily: "toast",
    contains: ["legumes"],
    breakfastType: "toast",
  }),
  mk("Гречка с яблоком и корицей", "завтр4-гречка-яблоко", {
    proteinType: "none",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: [],
    breakfastType: "porridge",
  }),
  mk("Рисовые безглютеновые хлебцы с томатом, зеленью и щепоткой соли", "завтр-r1-рис-crisp-томат", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "toast",
    contains: [],
    breakfastType: "toast",
  }),
  mk("Киноа с тёплыми овощами и зеленью", "завтр-r1-киноа-овощи", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "bowl",
    contains: [],
    breakfastType: "bowl",
  }),
  mk("Тыква дольками с травами и лёгкой корочкой", "завтр-r1-тыква-травы", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "stew",
    contains: [],
    breakfastType: "bowl",
  }),
  mk("Рисовые безглютеновые хлебцы с томатом, огурцом и зеленью", "завтр-r2-рис-crisp-томат-огурец", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "toast",
    contains: [],
    breakfastType: "toast",
  }),
  mk("Гречневые безглютеновые хлебцы с томатом и зеленью", "завтр-r2-греч-crisp-томат", {
    proteinType: "none",
    carbType: "buckwheat",
    mealFamily: "toast",
    contains: [],
    breakfastType: "toast",
  }),
  mk("Тёплая тыква с яблоком и корицей", "завтр-r2-тыква-яблоко", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "stew",
    contains: [],
    breakfastType: "bowl",
  }),
  mk("Запечённое яблоко с рисовыми безглютеновыми хлебцами", "завтр-r2-яблоко-crisp", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "toast",
    contains: [],
    breakfastType: "toast",
  }),
  mk("Картофельные дольки с укропом и огурцом", "завтр-r2-картофель-укроп", {
    proteinType: "none",
    carbType: "potato",
    mealFamily: "stew",
    contains: [],
    breakfastType: "bowl",
  }),
  mk("Тёплый салат из свёклы, огурца и зелени", "завтр-r2-салат-свекла-огурец", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "salad",
    contains: [],
    breakfastType: "bowl",
  }),
  mk("Овощная тарелка с картофелем и укропом", "завтр-r2-овощи-картофель", {
    proteinType: "none",
    carbType: "potato",
    mealFamily: "bowl",
    contains: [],
    breakfastType: "bowl",
  }),
  mk("Рисовые безглютеновые хлебцы с печёным яблоком и корицей", "завтр-r2-crisp-яблоко", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "toast",
    contains: [],
    breakfastType: "toast",
  }),
];

export const LUNCH_CATALOG: CatalogDish[] = [
  mk("Куриный суп с овощами и лапшой", "обед-суп-куриный", {
    proteinType: "chicken",
    carbType: "pasta",
    mealFamily: "soup",
    contains: ["meat", "gluten"],
    starchKey: "суп",
  }),
  mk("Суп с треской, картофелем и морковью", "обед-суп-рыбный", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "soup",
    contains: ["fish", "seaFish"],
    starchKey: "суп",
    dishSubtype: "fishMain",
  }),
  mk("Индейка с булгуром и салатом", "обед-булгур-индейка", {
    proteinType: "turkey",
    carbType: "bulgur",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "булгур",
  }),
  mk("Гречка с запечённой курицей и овощами", "обед-гречка-курица", {
    proteinType: "chicken",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "гречка",
  }),
  mk("Рис с запечённой треской и салатом", "обед-рис-рыба", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["fish", "seaFish"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Чечевица с тушёными овощами", "обед-чечевица", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "stew",
    contains: ["legumes"],
    starchKey: "бобовые",
  }),
  mk("Фасоль в томатном соусе с морковью", "обед-фасоль", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "stew",
    contains: ["legumes"],
    starchKey: "бобовые",
  }),
  mk("Паста из твёрдых сортов с курицей и овощами", "обед-паста-курица", {
    proteinType: "chicken",
    carbType: "pasta",
    mealFamily: "bowl",
    contains: ["meat", "gluten"],
    starchKey: "паста",
  }),
  mk("Запечённый картофель с минтаем и зеленью", "обед-картофель-рыба", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Салат-боул с курицей и авокадо", "обед-боул-курица", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "салат",
  }),
  mk("Салат-боул с тунцом и огурцом", "обед-боул-рыба", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["fish", "seaFish"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Салат-боул с яйцом и зеленью", "обед-боул-яйцо", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "salad",
    contains: ["egg"],
    starchKey: "салат",
    containsEgg: true,
  }),
  mk("Лёгкий борщ без зажарки", "обед-борщ", {
    proteinType: "mixed",
    carbType: "none",
    mealFamily: "soup",
    contains: ["meat"],
    starchKey: "суп",
  }),
  mk("Говядина тушёная с гречкой", "обед-говядина-гречка", {
    proteinType: "beef",
    carbType: "buckwheat",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "гречка",
  }),
  mk("Куриная грудка на пару с рисом", "обед-курица-рис", {
    proteinType: "chicken",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "рис",
  }),
  mk("Стейк из индейки с овощами", "обед-стейк-индейка", {
    proteinType: "turkey",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "салат",
  }),
  mk("Минестроне с фасолью", "обед-минестроне", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "soup",
    contains: ["legumes"],
    starchKey: "суп",
  }),
  mk("Треска с овощами и картофелем", "обед-треска", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Чечевичный суп", "обед-чечевичный-суп", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "soup",
    contains: ["legumes"],
    starchKey: "суп",
  }),
  mk("Кабачки с курицей на сковороде", "обед-кабачки-курица", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "салат",
  }),
  mk("Плов с курицей", "обед-плов", {
    proteinType: "chicken",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "рис",
  }),
  mk("Салат нисуаз с яйцом и тунцом", "обед-нисуаз", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "salad",
    contains: ["egg", "fish", "seaFish"],
    starchKey: "салат",
    containsEgg: true,
  }),
  mk("Фарш из индейки с гречкой", "обед-фарш-индейка", {
    proteinType: "turkey",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "гречка",
  }),
  mk("Рис с фасолью и овощами", "обед-рис-фасоль", {
    proteinType: "legumes",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["legumes"],
    starchKey: "рис",
  }),
  mk("Гуляш из говядины с картофелем", "обед-гуляш", {
    proteinType: "beef",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "картофель",
  }),
  mk("Куриная грудка с рисом и брокколи", "обед2-курица-рис-брокколи", {
    proteinType: "chicken",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "рис",
  }),
  mk("Суп-пюре из тыквы", "обед2-суп-тыква", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "soup",
    contains: [],
    starchKey: "суп",
  }),
  mk("Индейка с картофельным пюре", "обед2-индейка-пюре", {
    proteinType: "turkey",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "картофель",
  }),
  mk("Треска в фольге с лимоном", "обед2-рыба-фольга", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Салат с киноа и овощами", "обед2-киноа-салат", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "salad",
    contains: [],
    starchKey: "салат",
  }),
  mk("Куриные тефтели с гречкой", "обед2-тефтели-гречка", {
    proteinType: "chicken",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "гречка",
  }),
  mk("Нут с томатами и специями", "обед2-нут-томат", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "stew",
    contains: ["legumes"],
    starchKey: "бобовые",
  }),
  mk("Запечённая курица с овощами", "обед2-курица-запечённая", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "салат",
  }),
  mk("Рисовая лапша с курицей", "обед2-лапша-курица", {
    proteinType: "chicken",
    carbType: "pasta",
    mealFamily: "bowl",
    contains: ["meat", "gluten"],
    starchKey: "паста",
  }),
  mk("Тушёная говядина с морковью", "обед2-говядина-морковь", {
    proteinType: "beef",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "салат",
  }),
  mk("Суп с фрикадельками из индейки", "обед2-суп-фрикадельки", {
    proteinType: "turkey",
    carbType: "none",
    mealFamily: "soup",
    contains: ["meat"],
    starchKey: "суп",
  }),
  mk("Перловка с грибами", "обед2-перловка-грибы", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "bowl",
    contains: ["gluten"],
    starchKey: "гречка",
  }),
  mk("Салат Цезарь с курицей (без соуса с майонезом)", "обед2-цезарь-курица", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat", "dairy", "gluten"],
    starchKey: "салат",
  }),
  mk("Кабачки фаршированные курицей", "обед2-кабачки-фарш", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "салат",
  }),
  mk("Котлеты из хека с пюре", "обед2-рыбные-котлеты", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "seaFish", "egg"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Булгур с овощами и нутом", "обед2-булгур-нут", {
    proteinType: "legumes",
    carbType: "bulgur",
    mealFamily: "bowl",
    contains: ["legumes"],
    starchKey: "булгур",
  }),
  mk("Кролик тушёный с рисом", "обед2-кролик-рис", {
    proteinType: "rabbit",
    carbType: "rice",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "рис",
  }),
  mk("Овощной суп с перловкой", "обед2-суп-перловка", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "soup",
    contains: ["gluten"],
    starchKey: "суп",
  }),
  mk("Стейк из курицы с салатом", "обед2-стейк-курица", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat"],
    starchKey: "салат",
  }),
  mk("Паста с томатным соусом и индейкой", "обед2-паста-индейка", {
    proteinType: "turkey",
    carbType: "pasta",
    mealFamily: "bowl",
    contains: ["meat", "gluten"],
    starchKey: "паста",
  }),
  mk("Чечевица с курицей", "обед2-чечевица-курица", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat", "legumes"],
    starchKey: "бобовые",
  }),
  mk("Салат с тунцом и фасолью", "обед2-салат-тунец", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["fish", "seaFish", "legumes"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Картофель по-деревенски с индейкой", "обед2-картофель-индейка", {
    proteinType: "turkey",
    carbType: "potato",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "картофель",
  }),
  mk("Суп с чечевицей и шпинатом", "обед2-суп-чечевица-шпинат", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "soup",
    contains: ["legumes"],
    starchKey: "суп",
  }),
  mk("Гречка с грибами и луком", "обед2-гречка-грибы-лук", {
    proteinType: "none",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: [],
    starchKey: "гречка",
  }),
  mk("Рис с курицей и морковью", "обед3-рис-курица-морковь", {
    proteinType: "chicken",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "рис",
  }),
  mk("Гречка с индейкой и зеленью", "обед3-гречка-индейка", {
    proteinType: "turkey",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "гречка",
  }),
  mk("Паста с тунцом и овощами", "обед3-паста-тунец", {
    proteinType: "fish",
    carbType: "pasta",
    mealFamily: "bowl",
    contains: ["fish", "seaFish", "gluten"],
    starchKey: "паста",
    dishSubtype: "fishMain",
  }),
  mk("Суп с фасолью, овощами и зеленью", "обед3-суп-фасоль", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "soup",
    contains: ["legumes"],
    starchKey: "суп",
  }),
  mk("Картофель с куриной грудкой", "обед3-картофель-курица", {
    proteinType: "chicken",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "картофель",
  }),
  mk("Булгур с курицей и перцем", "обед3-булгур-курица", {
    proteinType: "chicken",
    carbType: "bulgur",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "булгур",
  }),
  mk("Рис с запечённым лососём", "обед3-рис-рыба", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["fish", "seaFish"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Чечевица с томатами и луком", "обед3-чечевица-томат", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "stew",
    contains: ["legumes"],
    starchKey: "бобовые",
  }),
  mk("Салат с курицей и перцем", "обед3-салат-курица", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat"],
    starchKey: "салат",
  }),
  mk("Суп с нутом и овощами", "обед3-суп-нут", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "soup",
    contains: ["legumes"],
    starchKey: "суп",
  }),
  mk("Лёгкий плов с курицей", "обед3-плов-курица", {
    proteinType: "chicken",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "рис",
  }),
  mk("Говядина тушёная с рисом", "обед3-говядина-рис", {
    proteinType: "beef",
    carbType: "rice",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "рис",
  }),
  mk("Треска с рисом и зеленью", "обед3-треска-рис", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["fish", "seaFish"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Салат с яйцом и овощами", "обед3-салат-яйцо", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "salad",
    contains: ["egg"],
    starchKey: "салат",
    containsEgg: true,
  }),
  mk("Индейка с картофелем и салатом", "обед3-индейка-картофель", {
    proteinType: "turkey",
    carbType: "potato",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "картофель",
  }),
  mk("Кролик с гречкой и овощами", "обед3-кролик-гречка", {
    proteinType: "rabbit",
    carbType: "buckwheat",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "гречка",
  }),
  mk("Гороховый суп без копчёностей", "обед3-суп-горох", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "soup",
    contains: ["legumes"],
    starchKey: "суп",
  }),
  mk("Паста с курицей и брокколи", "обед3-паста-брокколи", {
    proteinType: "chicken",
    carbType: "pasta",
    mealFamily: "bowl",
    contains: ["meat", "gluten"],
    starchKey: "паста",
  }),
  mk("Рис с овощами и яйцом", "обед3-рис-яйцо", {
    proteinType: "egg",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["egg"],
    starchKey: "рис",
    containsEgg: true,
  }),
  mk("Фасоль с курицей и томатом", "обед3-фасоль-курица", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat", "legumes"],
    starchKey: "бобовые",
  }),
  mk("Суп с минтаем и овощами", "обед3-суп-рыбный", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "soup",
    contains: ["fish", "seaFish"],
    starchKey: "суп",
    dishSubtype: "fishMain",
  }),
  mk("Гречка с котлетой из индейки", "обед3-гречка-котлета", {
    proteinType: "turkey",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "гречка",
  }),
  mk("Салат с тунцом и огурцом", "обед3-салат-тунец", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["fish", "seaFish"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Картофельное пюре с треской", "обед3-пюре-рыба", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Рагу из овощей с курицей", "обед3-рагу-курица", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "салат",
  }),
  mk("Рис с индейкой и кабачком", "обед3-рис-индейка", {
    proteinType: "turkey",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "рис",
  }),
  mk("Запечённый картофель со скумбрией", "обед3-картофель-рыба", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Овощной суп с чечевицей", "обед3-суп-чечевица", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "soup",
    contains: ["legumes"],
    starchKey: "суп",
  }),
  mk("Паста с индейкой и томатом", "обед3-паста-индейка", {
    proteinType: "turkey",
    carbType: "pasta",
    mealFamily: "bowl",
    contains: ["meat", "gluten"],
    starchKey: "паста",
  }),
  mk("Гречка с грибами и курицей", "обед3-гречка-грибы-курица", {
    proteinType: "chicken",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "гречка",
  }),
  mk("Рис с фасолью и овощами", "обед3-рис-фасоль", {
    proteinType: "legumes",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["legumes"],
    starchKey: "рис",
  }),
  mk("Салат с курицей и фетой", "обед3-салат-фета", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat", "dairy"],
    starchKey: "салат",
  }),
  mk("Курица тушёная с овощами", "обед3-курица-туш", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "салат",
  }),
  mk("Хек на пару с овощами", "обед3-рыба-пар", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Суп с вермишелью и курицей", "обед3-суп-вермишель", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "soup",
    contains: ["meat", "gluten"],
    starchKey: "суп",
  }),
  mk("Бобовый суп с курицей", "обед3-суп-бобовый", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "soup",
    contains: ["meat", "legumes"],
    starchKey: "суп",
  }),
  mk("Пшено с курицей и морковью", "обед3-пшено-курица", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "гречка",
  }),
  mk("Паста с лососем и шпинатом", "обед3-паста-рыба", {
    proteinType: "fish",
    carbType: "pasta",
    mealFamily: "bowl",
    contains: ["fish", "seaFish", "gluten"],
    starchKey: "паста",
    dishSubtype: "fishMain",
  }),
  mk("Гречка с кроликом и луком", "обед3-гречка-кролик", {
    proteinType: "rabbit",
    carbType: "buckwheat",
    mealFamily: "stew",
    contains: ["meat"],
    starchKey: "гречка",
  }),
  mk("Рис с говядиной и овощами", "обед3-рис-говядина", {
    proteinType: "beef",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["meat"],
    starchKey: "рис",
  }),
  mk("Чечевица с тушёными овощами", "обед4-чечевица-овощи", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "stew",
    contains: ["legumes"],
    starchKey: "бобовые",
  }),
  mk("Суп с нутом и морковью", "обед4-суп-нут", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "soup",
    contains: ["legumes"],
    starchKey: "суп",
  }),
  mk("Фасоль с овощами и томатом", "обед4-фасоль-овощи", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "stew",
    contains: ["legumes"],
    starchKey: "бобовые",
  }),
  mk("Рис с овощами и зеленью", "обед4-рис-овощи", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "bowl",
    contains: [],
    starchKey: "рис",
  }),
  mk("Булгур с овощами и зеленью", "обед4-булгур-овощи", {
    proteinType: "none",
    carbType: "bulgur",
    mealFamily: "bowl",
    contains: [],
    starchKey: "булгур",
  }),
  mk("Овощной суп с чечевицей", "обед4-суп-чечевица", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "soup",
    contains: ["legumes"],
    starchKey: "суп",
  }),
  mk("Салат с нутом и овощами", "обед4-салат-нут", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "salad",
    contains: ["legumes"],
    starchKey: "салат",
  }),
  mk("Пшено с тушёными овощами", "обед4-пшено-овощи", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "bowl",
    contains: [],
    starchKey: "гречка",
  }),
  mk("Киноа с овощами и зеленью", "обед4-киноа-овощи", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "bowl",
    contains: [],
    starchKey: "салат",
  }),
  mk("Суп с фасолью и шпинатом", "обед4-суп-фасоль-шпинат", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "soup",
    contains: ["legumes"],
    starchKey: "суп",
  }),
  mk("Гречка с хумусом и овощами", "обед4-гречка-хумус", {
    proteinType: "legumes",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["legumes"],
    starchKey: "гречка",
  }),
  mk("Гречка с яйцом и овощами", "обед4-гречка-яйцо", {
    proteinType: "egg",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["egg"],
    starchKey: "гречка",
    containsEgg: true,
  }),
  mk("Салат с яйцом и овощами", "обед4-салат-яйцо", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "salad",
    contains: ["egg"],
    starchKey: "салат",
    containsEgg: true,
  }),
  mk("Рагу из овощей и чечевицы", "обед4-рагу-чечевица", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "stew",
    contains: ["legumes"],
    starchKey: "бобовые",
  }),
  mk("Картофель с овощами", "обед4-картофель-овощи", {
    proteinType: "none",
    carbType: "potato",
    mealFamily: "stew",
    contains: [],
    starchKey: "картофель",
  }),
  mk("Рис с нутом и кабачком", "обед4-рис-нут", {
    proteinType: "legumes",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["legumes"],
    starchKey: "рис",
  }),
  mk("Овощной суп с яйцом", "обед4-суп-яйцо", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "soup",
    contains: ["egg"],
    starchKey: "суп",
    containsEgg: true,
  }),
  mk("Минестроне с фасолью и овощами", "обед4-минестроне", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "soup",
    contains: ["legumes"],
    starchKey: "суп",
  }),
  mk("Гречка с грибами и зеленью", "обед4-гречка-грибы", {
    proteinType: "none",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: [],
    starchKey: "гречка",
  }),
  mk("Рис с фасолью и перцем", "обед4-рис-фасоль-перец", {
    proteinType: "legumes",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["legumes"],
    starchKey: "рис",
  }),
  mk("Хек с рисом и салатом", "обед4-хек-рис", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["fish", "seaFish"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Лосось с картофелем и зеленью", "обед4-лосось-картофель", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Семга на пару с брокколи", "обед4-семга-пар", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Скумбрия с салатом", "обед4-скумбрия-салат", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["fish", "seaFish"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Суп с хеком и овощами", "обед4-суп-хек", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "soup",
    contains: ["fish", "seaFish"],
    starchKey: "суп",
    dishSubtype: "fishMain",
  }),
  mk("Форель запечённая с лимоном", "обед4-форель-лимон", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Судак с картофелем", "обед4-судак-картофель", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Щука запечённая с овощами", "обед4-щука-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    dishSubtype: "fishMain",
  }),
  mk("Карп тушёный с овощами", "обед4-карп-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    dishSubtype: "fishMain",
  }),
  mk("Окунь с рисом", "обед4-окунь-рис", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["fish", "riverFish"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Суп с судаком и морковью", "обед4-суп-судак", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "soup",
    contains: ["fish", "riverFish"],
    starchKey: "суп",
    dishSubtype: "fishMain",
  }),
  mk("Салат с щукой и овощами", "обед4-салат-щука", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["fish", "riverFish"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Судак на пару с брокколи", "обед4-судак-пар", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    dishSubtype: "fishMain",
  }),
  mk("Щука с гречкой", "обед4-щука-гречка", {
    proteinType: "fish",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["fish", "riverFish"],
    starchKey: "гречка",
    dishSubtype: "fishMain",
  }),
  mk("Креветки с рисом", "обед4-креветки-рис", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["seafood"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Мидии с овощами", "обед4-мидии-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["seafood"],
    dishSubtype: "fishMain",
  }),
  mk("Кальмар с салатом", "обед4-кальмар-салат", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["seafood"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Креветки на пару с овощами", "обед4-креветки-пар", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["seafood"],
    dishSubtype: "fishMain",
  }),
  mk("Мидии в томатном соусе", "обед4-мидии-томат", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["seafood"],
    dishSubtype: "fishMain",
  }),
  mk("Кальмар с картофелем", "обед4-кальмар-картофель", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["seafood"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Хек с овощным салатом", "обед4-краб-салат", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["fish", "seaFish"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Мидии в томатном соусе с овощами", "обед4-раки-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["seafood"],
    dishSubtype: "fishMain",
  }),
  mk("Минтай с морковью и овощами", "обед4-осьминог-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Минтай, запечённый с морковью и луком", "обед5-минтай-морковь-лук", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Минтай в томатном соусе с рисом", "обед5-минтай-томат-рис", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["fish", "seaFish"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Хек, тушённый с овощами", "обед5-хек-тушение-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Хек с рисом, укропом и огурцом", "обед5-хек-рис-укроп", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["fish", "seaFish"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Треска с гречкой и огуречным салатом", "обед5-треска-гречка-огурец", {
    proteinType: "fish",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["fish", "seaFish"],
    starchKey: "гречка",
    dishSubtype: "fishMain",
  }),
  mk("Треска с картофелем и укропом", "обед5-треска-картофель-укроп", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Судак, запечённый с морковью и зеленью", "обед5-судак-морковь-зелень", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    dishSubtype: "fishMain",
  }),
  mk("Щука в котлетах с гречкой", "обед5-щука-котлеты-гречка", {
    proteinType: "fish",
    carbType: "buckwheat",
    mealFamily: "stew",
    contains: ["fish", "riverFish", "egg"],
    starchKey: "гречка",
    dishSubtype: "fishMain",
    containsEgg: true,
  }),
  mk("Окунь, запечённый с овощами", "обед5-окунь-запеченный", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    dishSubtype: "fishMain",
  }),
  mk("Карп, тушённый с морковью и луком", "обед5-карп-морковь-лук", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    dishSubtype: "fishMain",
  }),
  mk("Кальмар с рисом и овощами", "обед5-кальмар-рис-овощи", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["seafood"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Кальмар, тушённый с морковью и зеленью", "обед5-кальмар-морковь-зелень", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["seafood"],
    dishSubtype: "fishMain",
  }),
  mk("Мидии в томатном соусе с рисом", "обед5-мидии-томат-рис", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["seafood"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Креветки с рисом и огуречным салатом", "обед5-креветки-рис-огурец", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["seafood"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Щука, запечённая с морковью и луком", "обед6-щука-морковь-лук", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    dishSubtype: "fishMain",
  }),
  mk("Сом, тушённый с овощами", "обед6-сом-тушение-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    dishSubtype: "fishMain",
  }),
  mk("Сом с рисом и зеленью", "обед6-сом-рис-зелень", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["fish", "riverFish"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Карась, запечённый с картофелем", "обед6-карась-картофель", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Карась с овощным салатом", "обед6-карась-салат", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["fish", "riverFish"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Лещ, запечённый с луком и морковью", "обед6-лещ-морковь-лук", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    dishSubtype: "fishMain",
  }),
  mk("Лещ с гречкой и огуречным салатом", "обед6-лещ-гречка-огурец", {
    proteinType: "fish",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["fish", "riverFish"],
    starchKey: "гречка",
    dishSubtype: "fishMain",
  }),
  mk("Окунь с картофелем и укропом", "обед6-окунь-картофель-укроп", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Карп с гречкой и салатом", "обед6-карп-гречка-салат", {
    proteinType: "fish",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: ["fish", "riverFish"],
    starchKey: "гречка",
    dishSubtype: "fishMain",
  }),
  mk("Лещ с рисом и овощами", "обед6-лещ-рис-овощи", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["fish", "riverFish"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Кефаль, запечённая с лимоном и зеленью", "обед6-кефаль-лимон-зелень", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Кефаль с картофелем и овощным салатом", "обед6-кефаль-картофель-салат", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Картофель дольками с паприкой и зелёным салатом", "обед-r1-картофель-салат", {
    proteinType: "none",
    carbType: "potato",
    mealFamily: "stew",
    contains: [],
    starchKey: "картофель",
  }),
  mk("Рис с томлёными овощами и зеленью", "обед-r1-рис-овощи-зелень", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "bowl",
    contains: [],
    starchKey: "рис",
  }),
  mk("Капуста, тушённая с морковью и томатом", "обед-r1-капуста-морковь", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "stew",
    contains: [],
    starchKey: "салат",
  }),
];

export const DINNER_CATALOG: CatalogDish[] = [
  mk("Запечённая скумбрия с овощами", "ужин-рыба-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Индейка тушёная с овощами", "ужин-индейка", {
    proteinType: "turkey",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Омлет с салатом из свежих овощей", "ужин-омлет-салат", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Творог с зеленью и овощами", "ужин-творог", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
  }),
  mk("Салат с яйцом, сыром и овощами", "ужин-салат-яйцо-сыр", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "salad",
    contains: ["egg", "dairy"],
    containsEgg: true,
  }),
  mk("Курица с тушёными овощами", "ужин-курица", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Овощное рагу с фасолью и томатом", "ужин-рагу-фасоль", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "stew",
    contains: ["legumes"],
  }),
  mk("Овощная запеканка с яйцом", "ужин-запеканка-овощ-яйцо", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "casserole",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Творожная запеканка с салатом", "ужин-запеканка-творог", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "casserole",
    contains: ["dairy", "egg"],
    dishSubtype: "tvorogBake",
  }),
  mk("Треска на пару с брокколи", "ужин-рыба-пар", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Кролик с овощами", "ужин-кролик", {
    proteinType: "rabbit",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Салат с индейкой", "ужин-салат-индейка", {
    proteinType: "turkey",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat"],
  }),
  mk("Куриные котлеты на пару с овощами", "ужин-котлеты-курица", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Запечённая индейка с кабачками", "ужин-индейка-кабачки", {
    proteinType: "turkey",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Чечевица с салатом", "ужин-чечевица-салат", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "salad",
    contains: ["legumes"],
  }),
  mk("Салат с тунцом и овощами", "ужин-салат-тунец", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Говядина с тушёными овощами", "ужин-говядина", {
    proteinType: "beef",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Салат с нутом и овощами", "ужин-нут-салат", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "salad",
    contains: ["legumes"],
  }),
  mk("Яйцо пашот с овощами", "ужин-пашот", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Курица с рисом и зеленью", "ужин-курица-рис", {
    proteinType: "chicken",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["meat"],
  }),
  mk("Овощи с хумусом", "ужин-овощи-хумус", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "bowl",
    contains: ["legumes"],
  }),
  mk("Запечённая треска с салатом", "ужин-треска", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Куриная грудка на гриле с салатом", "ужин2-курица-гриль", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat"],
  }),
  mk("Тушёная индейка с кабачками", "ужин2-индейка-кабачки", {
    proteinType: "turkey",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Салат с авокадо и яйцом", "ужин2-салат-авокадо-яйцо", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "salad",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Минтай с овощами на пару", "ужин2-рыба-пар-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Творожная запеканка с ягодами", "ужин2-запеканка-ягоды", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "casserole",
    contains: ["dairy", "egg"],
    dishSubtype: "tvorogBake",
  }),
  mk("Омлет с грибами и сыром", "ужин2-омлет-грибы", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg", "dairy"],
    containsEgg: true,
  }),
  mk("Фасоль с томатным соусом", "ужин2-фасоль-томат", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "stew",
    contains: ["legumes"],
  }),
  mk("Кролик с морковью", "ужин2-кролик-морковь", {
    proteinType: "rabbit",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Салат с курицей и огурцом", "ужин2-салат-курица-огурец", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat"],
  }),
  mk("Говядина с болгарским перцем", "ужин2-говядина-перец", {
    proteinType: "beef",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Чечевица с зеленью", "ужин2-чечевица-зелень", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "bowl",
    contains: ["legumes"],
  }),
  mk("Запечённая курица с брокколи", "ужин2-курица-брокколи", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Салат с сельдью и картофелем", "ужин2-сельдь-картофель", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "salad",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Овощи с сыром запечённые", "ужин2-овощи-сыр", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "casserole",
    contains: ["dairy"],
  }),
  mk("Индейка с салатом из капусты", "ужин2-индейка-капуста", {
    proteinType: "turkey",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat"],
  }),
  mk("Яйца всмятку с зеленью", "ужин2-яйца-зелень", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Тефтели из трески с овощами", "ужин2-рыбные-тефтели", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish", "egg"],
    dishSubtype: "fishMain",
  }),
  mk("Салат с нутом и фетой", "ужин2-нут-фета", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "salad",
    contains: ["legumes", "dairy"],
  }),
  mk("Курица с перцем и луком", "ужин2-курица-перец", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Творог с огурцом и укропом", "ужин2-творог-огурец", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
  }),
  mk("Куриная грудка с салатом из огурца", "ужин3-курица-салат", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat"],
  }),
  mk("Лосось запечённый с овощами", "ужин3-рыба-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Омлет с зеленью и салатом", "ужин3-омлет-зелень", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Творог с помидором", "ужин3-творог-помидор", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
  }),
  mk("Индейка с тушёными овощами", "ужин3-индейка-овощи", {
    proteinType: "turkey",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Салат с тунцом и яйцом", "ужин3-салат-тунец", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["fish", "seaFish", "egg"],
    dishSubtype: "fishMain",
    containsEgg: true,
  }),
  mk("Творожная запеканка с ягодами", "ужин3-запеканка-ягоды", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "casserole",
    contains: ["dairy", "egg"],
    dishSubtype: "tvorogBake",
  }),
  mk("Котлеты из индейки с салатом", "ужин3-котлеты-индейка", {
    proteinType: "turkey",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Хек на пару с брокколи", "ужин3-рыба-брокколи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Яичница с овощами", "ужин3-яичница-овощи", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Творог с зеленью", "ужин3-творог-зелень", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
  }),
  mk("Курица с кабачком и томатом", "ужин3-курица-кабачок", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Салат с курицей и авокадо", "ужин3-салат-авокадо", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat"],
  }),
  mk("Треска с салатом", "ужин3-треска-салат", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Сырники со сметаной", "ужин3-сырники", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "casserole",
    contains: ["dairy", "egg"],
    dishSubtype: "syrniki",
  }),
  mk("Говядина тушёная с овощами", "ужин3-говядина-овощи", {
    proteinType: "beef",
    carbType: "none",
    mealFamily: "stew",
    contains: ["meat"],
  }),
  mk("Салат с яйцом и огурцом", "ужин3-салат-яйцо", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "salad",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Творог с перцем", "ужин3-творог-перец", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
  }),
  mk("Кролик с салатом из капусты", "ужин3-кролик-салат", {
    proteinType: "rabbit",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat"],
  }),
  mk("Треска с лимоном и зеленью", "ужин3-рыба-лимон", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Скрэмбл с помидором", "ужин3-скрэмбл", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Творожный салат с овощами", "ужин3-творожный-салат", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "salad",
    contains: ["dairy"],
  }),
  mk("Индейка с салатом из моркови", "ужин3-индейка-морковь", {
    proteinType: "turkey",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat"],
  }),
  mk("Салат с тунцом и фасолью", "ужин3-салат-рыба-фасоль", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["fish", "seaFish", "legumes"],
    dishSubtype: "fishMain",
  }),
  mk("Запеканка из творога с яблоком", "ужин3-запеканка-яблоко", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "casserole",
    contains: ["dairy", "egg"],
    dishSubtype: "tvorogBake",
  }),
  mk("Курица с салатом из свёклы", "ужин3-курица-свекла", {
    proteinType: "chicken",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat"],
  }),
  mk("Котлеты из минтая с овощами", "ужин3-рыбные-котлеты", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish", "egg"],
    dishSubtype: "fishMain",
    containsEgg: true,
  }),
  mk("Омлет с сыром", "ужин3-омлет-сыр", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "omelet",
    contains: ["egg", "dairy"],
    containsEgg: true,
  }),
  mk("Творог с огурцом", "ужин3-творог-огурец", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "dairyBowl",
    contains: ["dairy"],
  }),
  mk("Салат с индейкой и зеленью", "ужин3-салат-индейка", {
    proteinType: "turkey",
    carbType: "none",
    mealFamily: "salad",
    contains: ["meat"],
  }),
  mk("Чечевица с овощами", "ужин4-чечевица-овощи", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "stew",
    contains: ["legumes"],
  }),
  mk("Тёплый салат с нутом и зеленью", "ужин4-салат-нут", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "salad",
    contains: ["legumes"],
  }),
  mk("Овощное рагу с фасолью и томатом", "ужин4-рагу-фасоль", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "stew",
    contains: ["legumes"],
  }),
  mk("Гречка с грибами", "ужин4-гречка-грибы", {
    proteinType: "none",
    carbType: "buckwheat",
    mealFamily: "bowl",
    contains: [],
  }),
  mk("Рис с тушёными овощами", "ужин4-рис-овощи", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "bowl",
    contains: [],
  }),
  mk("Тёплый салат с яйцом и зеленью", "ужин4-салат-яйцо", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "salad",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Тёплый салат с чечевицей", "ужин4-салат-чечевица", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "salad",
    contains: ["legumes"],
  }),
  mk("Картофель с овощами и зеленью", "ужин4-картофель-овощи", {
    proteinType: "none",
    carbType: "potato",
    mealFamily: "stew",
    contains: [],
  }),
  mk("Хумус с овощами", "ужин4-хумус-овощи", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "salad",
    contains: ["legumes"],
  }),
  mk("Овощное рагу с чечевицей", "ужин4-рагу-чечевица", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "stew",
    contains: ["legumes"],
  }),
  mk("Судак с овощами", "ужин4-судак-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    dishSubtype: "fishMain",
  }),
  mk("Щука с салатом", "ужин4-щука-салат", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["fish", "riverFish"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Креветки с овощами", "ужин4-креветки-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["seafood"],
    dishSubtype: "fishMain",
  }),
  mk("Мидии с салатом", "ужин4-мидии-салат", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "salad",
    contains: ["seafood"],
    starchKey: "салат",
    dishSubtype: "fishMain",
  }),
  mk("Кальмар с овощами", "ужин4-кальмар-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["seafood"],
    dishSubtype: "fishMain",
  }),
  mk("Скумбрия, запечённая с лимоном и картофелем", "ужин5-скумбрия-лимон-картофель", {
    proteinType: "fish",
    carbType: "potato",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    starchKey: "картофель",
    dishSubtype: "fishMain",
  }),
  mk("Горбуша с рисом и тёплыми овощами", "ужин5-горбуша-рис-овощи", {
    proteinType: "fish",
    carbType: "rice",
    mealFamily: "bowl",
    contains: ["fish", "seaFish"],
    starchKey: "рис",
    dishSubtype: "fishMain",
  }),
  mk("Карась с тушёными овощами", "ужин6-карась-овощи", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "riverFish"],
    dishSubtype: "fishMain",
  }),
  mk("Кефаль, тушённая с морковью и луком", "ужин6-кефаль-морковь-лук", {
    proteinType: "fish",
    carbType: "none",
    mealFamily: "stew",
    contains: ["fish", "seaFish"],
    dishSubtype: "fishMain",
  }),
  mk("Грибы с картофелем и морковью", "ужин-грибы-картофель-морковь", {
    proteinType: "none",
    carbType: "potato",
    mealFamily: "stew",
    contains: [],
    starchKey: "картофель",
  }),
  mk("Перец, запечённый с рисом и овощами", "ужин-перец-рис-овощи-запеч", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "bowl",
    contains: [],
    starchKey: "рис",
  }),
  mk("Кабачки и баклажаны с чесноком под лёгкой корочкой", "ужин-r1-кабач-баклажан", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "stew",
    contains: [],
    starchKey: "салат",
  }),
  mk("Тёплый салат из запечённых овощей с зеленью", "ужин-r1-салат-запеч-овощи", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "salad",
    contains: [],
    starchKey: "салат",
  }),
];

export const SNACK_CATALOG: CatalogDish[] = [
  mk("Йогурт с фруктом", "перекус-йогурт-фрукт", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Творог с ягодами", "перекус-творог-ягоды", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Кефир 250 мл", "перекус-кефир", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Ряженка с фруктом", "перекус-ряженка", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Овощная нарезка с сыром", "перекус-овощи-сыр", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Яйцо вкрутую и огурец", "перекус-яйцо", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "snack",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Фрукт и горсть орехов", "перекус-фрукт-орехи", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: ["nuts"],
  }),
  mk("Цельнозерновой тост с сыром", "перекус-тост-сыр", {
    proteinType: "dairy",
    carbType: "bread",
    mealFamily: "snack",
    contains: ["dairy", "gluten"],
  }),
  mk("Хумус с овощными палочками", "перекус-хумус", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "snack",
    contains: ["legumes"],
  }),
  mk("Яблоко с арахисовой пастой (тонкий слой)", "перекус-яблоко-паста", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: ["nuts"],
  }),
  mk("Банан и кефир", "перекус-банан-кефир", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Сыр и помидоры черри", "перекус-сыр-томат", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Овощная нарезка с хумусом", "перекус-хумус-бл", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "snack",
    contains: ["legumes"],
  }),
  mk("Цельнозерновой тост с авокадо", "перекус-тост-авокадо", {
    proteinType: "none",
    carbType: "bread",
    mealFamily: "snack",
    contains: ["gluten"],
  }),
  mk("Фрукт и семечки", "перекус-семечки", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Рисовые хлебцы с индейкой", "перекус-хлебцы-индейка", {
    proteinType: "turkey",
    carbType: "rice",
    mealFamily: "snack",
    contains: ["meat"],
  }),
  mk("Смузи: банан и овсянка на воде", "перекус-смузи", {
    proteinType: "none",
    carbType: "oats",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Горсть орехов и фрукт", "перекус-орехи", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: ["nuts"],
  }),
  mk("Овощи и хумус", "перекус-овощи-хумус", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "snack",
    contains: ["legumes"],
  }),
  mk("Фрукт и рисовые хлебцы", "перекус-фрукт-хлебцы", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Творожный крем с ягодами", "перекус-творожный-крем", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Сырники мини запечённые", "перекус-сырники-мини", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy", "egg", "gluten"],
    dishSubtype: "syrniki",
  }),
  mk("Огурец и сыр", "перекус-огурец-сыр", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Яблоко и сыр", "перекус-яблоко-сыр", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Рисовые хлебцы с авокадо", "перекус-хлебцы-авокадо", {
    proteinType: "none",
    carbType: "rice",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Овощной смузи с кефиром", "перекус-овощной-смузи", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Греческий йогурт с орехами", "перекус-йогурт-орехи", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy", "nuts"],
  }),
  mk("Фрукт и хумус", "перекус-фрукт-хумус", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "snack",
    contains: ["legumes"],
  }),
  mk("Сыр и рисовые хлебцы", "перекус-сыр-хлебцы", {
    proteinType: "dairy",
    carbType: "rice",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Морковные палочки с хумусом", "перекус2-морковь-хумус", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "snack",
    contains: ["legumes"],
  }),
  mk("Кефир с корицей", "перекус2-кефир-корица", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Сырные палочки с овощами", "перекус2-сырные-палочки", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Груша и сыр", "перекус2-груша-сыр", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Рисовые хлебцы с индейкой", "перекус2-хлебцы-индейка", {
    proteinType: "turkey",
    carbType: "rice",
    mealFamily: "snack",
    contains: ["meat"],
  }),
  mk("Творожный крем с мёдом-заменителем", "перекус2-творожный-мед", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Овощной салат с маслом", "перекус2-овощной-салат", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Яйцо и помидор черри", "перекус2-яйцо-томат", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "snack",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Йогурт с семечками", "перекус2-йогурт-семечки", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Сырники мини с ягодным соусом", "перекус2-сырники-соус", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy", "egg", "gluten"],
    dishSubtype: "syrniki",
  }),
  mk("Фруктовый салат", "перекус2-фруктовый-салат", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Тост с авокадо", "перекус2-тост-авокадо", {
    proteinType: "none",
    carbType: "bread",
    mealFamily: "snack",
    contains: ["gluten"],
  }),
  mk("Сыр с орехами", "перекус2-сыр-орехи", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy", "nuts"],
  }),
  mk("Ряженка с корицей", "перекус2-ряженка", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Огурец и хумус", "перекус2-огурец-хумус", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "snack",
    contains: ["legumes"],
  }),
  mk("Банан и творог", "перекус2-банан-творог", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Сыр и виноград", "перекус2-сыр-виноград", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Кефир с бананом", "перекус2-кефир-банан", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Овощи с гуакамоле", "перекус2-овощи-гуакамоле", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Густой йогурт с ягодами", "перекус2-йогурт-густой", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Яблоко и горсть орехов", "перекус3-яблоко-орехи", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: ["nuts"],
  }),
  mk("Творог с ягодами", "перекус3-творог-ягоды", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Кефир с корицей", "перекус3-кефир-корица", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Огурец и сыр", "перекус3-огурец-сыр", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Груша и йогурт", "перекус3-груша-йогурт", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Морковь и хумус", "перекус3-морковь-хумус", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "snack",
    contains: ["legumes"],
  }),
  mk("Банан и кефир", "перекус3-банан-кефир", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Сыр и помидор", "перекус3-сыр-помидор", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Йогурт с мёдом", "перекус3-йогурт-мед", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Овощные палочки с творогом", "перекус3-овощи-творог", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Хлебец с авокадо", "перекус3-хлебец-авокадо", {
    proteinType: "none",
    carbType: "bread",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Творог с мёдом", "перекус3-творог-мед", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Сливы и орехи", "перекус3-сливы-орехи", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: ["nuts"],
  }),
  mk("Ряженка", "перекус3-ряженка", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Перец и сыр", "перекус3-перец-сыр", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Ягоды и йогурт", "перекус3-ягоды-йогурт", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Огурец и творог", "перекус3-огурец-творог", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Банан и йогурт", "перекус3-банан-йогурт", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Сыр и огурец", "перекус3-сыр-огурец", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Кефир с бананом", "перекус3-кефир-банан", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Хумус с овощами", "перекус3-хумус-овощи", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "snack",
    contains: ["legumes"],
  }),
  mk("Творог с фруктом", "перекус3-творог-фрукт", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Яблоко и сыр", "перекус3-яблоко-сыр", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Йогурт с семечками", "перекус3-йогурт-семечки", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Орехи и сухофрукты", "перекус3-орехи-сухофрукты", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: ["nuts"],
  }),
  mk("Творог с укропом", "перекус3-творог-укроп", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Сыр и груша", "перекус3-сыр-груша", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Киви и йогурт", "перекус3-киви-йогурт", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Морковь и творог", "перекус3-морковь-творог", {
    proteinType: "dairy",
    carbType: "none",
    mealFamily: "snack",
    contains: ["dairy"],
  }),
  mk("Банан и орехи", "перекус3-банан-орехи", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: ["nuts"],
  }),
  mk("Яблоко и рисовые хлебцы", "перекус4-яблоко-хлебцы", {
    proteinType: "none",
    carbType: "bread",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Груша и рисовые хлебцы", "перекус4-груша-хлебцы", {
    proteinType: "none",
    carbType: "bread",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Огурец и хумус", "перекус4-огурец-хумус", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "snack",
    contains: ["legumes"],
  }),
  mk("Морковь и хумус", "перекус4-морковь-хумус", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "snack",
    contains: ["legumes"],
  }),
  mk("Перец и хумус", "перекус4-перец-хумус", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "snack",
    contains: ["legumes"],
  }),
  mk("Яйцо и огурец", "перекус4-яйцо-огурец", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "snack",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Авокадо и рисовые хлебцы", "перекус4-авокадо-хлебцы", {
    proteinType: "none",
    carbType: "bread",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Банан и семечки", "перекус4-банан-семечки", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: ["nuts"],
  }),
  mk("Сливы и семечки", "перекус4-сливы-семечки", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: ["nuts"],
  }),
  mk("Овощные палочки с хумусом", "перекус4-овощи-хумус", {
    proteinType: "legumes",
    carbType: "none",
    mealFamily: "snack",
    contains: ["legumes"],
  }),
  mk("Фрукт и семечки", "перекус4-фрукт-семечки", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: ["nuts"],
  }),
  mk("Хлебец с авокадо", "перекус4-хлебец-авокадо", {
    proteinType: "none",
    carbType: "bread",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Яблоко и орехи", "перекус4-яблоко-орехи", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: ["nuts"],
  }),
  mk("Яйца вкрутую с овощами", "перекус4-яйца-овощи", {
    proteinType: "egg",
    carbType: "none",
    mealFamily: "snack",
    contains: ["egg"],
    containsEgg: true,
  }),
  mk("Гранат и орехи", "перекус4-гранат-орехи", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: ["nuts"],
  }),
  mk("Запечённое яблоко с корицей", "перекус-яблоко-запеч-корица", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Тыква дольками с паприкой", "перекус-тыква-дольки-паприка", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Свёкла отварная с укропом и лимоном", "перекус-свекла-укроп-лимон", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Морковь дольками с паприкой и зеленью", "перекус-r1-морковь-паприка", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: [],
  }),
  mk("Огуречный салат с укропом и каплей лимона", "перекус-r1-огурец-укроп", {
    proteinType: "none",
    carbType: "none",
    mealFamily: "snack",
    contains: [],
  }),
];
