export type Screen =
  | "start"
  | "about"
  | "questionnaire"
  | "building"
  | "nutritionPlan"
  | "dashboard"
  | "calendar"
  | "day"
  | "recommendations"
  | "progress"
  | "history"
  | "finish"
  | "updates"
  | "settings";
